# Generated by Django 5.2.14 on 2026-05-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('party', 'Party / Ledger'), ('simple', 'Simple Customer')], default='party', max_length=10),
        ),
    ]
