# Generated by Django 5.2.14 on 2026-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_organization_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Bill', 'verbose_name_plural': 'Customer Bills'},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={'verbose_name': 'Bill Item', 'verbose_name_plural': 'Bill Items'},
        ),
    ]
