# Generated by Django 5.2.14 on 2026-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_organization_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Purchase Item', 'verbose_name_plural': 'Purchase Items'},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Supplier Payment', 'verbose_name_plural': 'Supplier Payments'},
        ),
    ]
