# Generated by Django 5.2.14 on 2026-05-30 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_bill_bill_type'),
        ('customers', '0003_customer_portal_username'),
        ('products', '0005_alter_product_minimum_stock_alter_product_sale_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_type', models.CharField(choices=[('refund', 'Refund'), ('credit_note', 'Credit Note'), ('exchange', 'Exchange')], default='refund', max_length=20)),
                ('refund_mode', models.CharField(choices=[('ledger_credit', 'Ledger Credit'), ('cash', 'Cash Refund'), ('upi', 'UPI Refund'), ('store_credit', 'Store Credit')], default='ledger_credit', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cash/UPI actually refunded to customer', max_digits=12)),
                ('exchange_new_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exchange_net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Positive = customer pays; negative = credit to customer', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='customers.customer')),
                ('exchange_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_returns', to='billing.bill')),
                ('original_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='billing.bill')),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('original_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='billing.billitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.salesreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StoreCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_credit', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credit_txns', to='billing.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_credit_txns', to='customers.customer')),
                ('sales_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_credit_txns', to='returns.salesreturn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
