# Generated by Django 5.2.14 on 2026-06-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_organization_tenant'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_number',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='salesreturn',
            unique_together={('organization', 'return_number')},
        ),
    ]
