# Generated by Django 5.2.14 on 2026-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_organization_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-return_date', '-id'], 'verbose_name': 'Sales Return', 'verbose_name_plural': 'Sales Returns'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'ordering': ['id'], 'verbose_name': 'Sales Return Item', 'verbose_name_plural': 'Sales Return Items'},
        ),
        migrations.AlterModelOptions(
            name='storecreditbalance',
            options={'verbose_name': 'Store Credit Balance', 'verbose_name_plural': 'Store Credit Balances'},
        ),
        migrations.AlterModelOptions(
            name='storecredittransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store Credit Transaction', 'verbose_name_plural': 'Store Credit Transactions'},
        ),
    ]
