# Generated by Django 5.2.17 on 2026-09-21 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_logins', to='accounts.organization')),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_logins', to=settings.AUTH_USER_MODEL)),
                ('support_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support login',
                'verbose_name_plural': 'Support logins',
                'ordering': ['-created_at'],
            },
        ),
    ]
