# Generated by Django 5.2.14 on 2026-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagequeue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Queued Message', 'verbose_name_plural': 'Queued Messages'},
        ),
    ]
