# Generated by Django 5.2.14 on 2026-06-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_organization_tenant'),
        ('customers', '0003_customer_portal_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'code')},
        ),
    ]
