# Generated by Django 5.2.14 on 2026-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_organization_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_wholesale',
            field=models.BooleanField(default=True),
        ),
    ]
