# Generated by Django 5.2.14 on 2026-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_is_wholesale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['shop_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='partyproductrate',
            options={'ordering': ['product__name'], 'verbose_name': 'Party Product Rate', 'verbose_name_plural': 'Party Product Rates'},
        ),
    ]
