# Generated by Django 5.2.14 on 2026-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Wholesale Smart Ledger', max_length=200)),
                ('logo', models.FileField(blank=True, null=True, upload_to='business/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('invoice_prefix', models.CharField(default='BILL', max_length=10)),
                ('invoice_footer', models.TextField(blank=True, default='Thank you for your business!')),
                ('gst_enabled', models.BooleanField(default=True)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dark_mode', models.BooleanField(default=False)),
                ('auto_backup', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business settings',
            },
        ),
    ]
