# Generated by Django 5.2.14 on 2026-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='customer_option_desc',
            field=models.CharField(default='View your bills, dues & ledger with code + phone', max_length=300),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='customer_option_title',
            field=models.CharField(default='Customer', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='home_subtitle',
            field=models.CharField(default='Choose how you want to continue', max_length=300),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='home_title',
            field=models.CharField(default='Plumbing Smart Ledger', max_length=200),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='wholesale_option_desc',
            field=models.CharField(default='Owner login — billing, stock, suppliers, reports', max_length=300),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='wholesale_option_title',
            field=models.CharField(default='Wholesale / Shop', max_length=100),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_name',
            field=models.CharField(default='Plumbing Smart Ledger', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='invoice_footer',
            field=models.TextField(blank=True, default='Thank you! Quality plumbing materials.'),
        ),
    ]
