# Generated by Django 5.2.14 on 2026-06-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_organization_tenant'),
        ('business', '0004_businesssettings_owner_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_name',
            field=models.CharField(default='Smart Ledger Shop', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='customer_option_desc',
            field=models.CharField(default='Login with customer code and phone to view billing history', max_length=300),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='gst_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='home_title',
            field=models.CharField(default='Smart Ledger', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='invoice_footer',
            field=models.TextField(blank=True, default='Thank you! All prices are inclusive of tax.'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='wholesale_option_desc',
            field=models.CharField(default='Parties with ledger, credit, stock & reports', max_length=300),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='wholesale_option_title',
            field=models.CharField(default='Wholesale / Parties', max_length=100),
        ),
    ]
