# Generated by Django 5.2.14 on 2026-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_organization_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Set when the shop has saved business details in Settings.'),
        ),
    ]
