# Generated by Django 5.2.14 on 2026-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_setup_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssettings',
            options={'verbose_name': 'Business Setting', 'verbose_name_plural': 'Business Settings'},
        ),
    ]
