# Generated by Django 5.2.14 on 2026-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_businesssettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='whatsapp_manual_send',
            field=models.BooleanField(default=False, help_text='Draft WhatsApp messages manually in browser instead of automated background sending.'),
        ),
    ]
