# Generated by Django 5.2.15 on 2026-08-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesssettings_whatsapp_manual_send'),
    ]

    operations = [
        # Duplicate of 0009_..._and_more; keep graph, do not remove the field twice.
    ]
