# Generated by Django 5.2.14 on 2026-07-30 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businesssettings_whatsapp_manual_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssettings',
            name='whatsapp_manual_send',
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
