# Generated by Django 5.2.15 on 2026-09-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_businesssettings_whatsapp_manual_send'),
        ('business', '0009_remove_businesssettings_whatsapp_manual_send_and_more'),
    ]

    operations = [
    ]
