# Generated by Django 5.2.14 on 2026-05-30 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_backfill_stock_alert_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=0, help_text='Auto-set to 20% of stock when stock is added or increased.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale / party price (inclusive)', max_digits=10),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('return_cancel', 'Return Cancelled'), ('cancel', 'Bill Cancel'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
