# Generated by Django 5.2.14 on 2026-06-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_organization_tenant'),
        ('products', '0005_alter_product_minimum_stock_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'code')},
        ),
    ]
