# Generated by Django 5.2.14 on 2026-06-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_organization_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
