# Generated by Django 5.2.14 on 2026-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_opening_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening stock'), ('sale', 'Sale'), ('return', 'Return'), ('return_cancel', 'Return Cancelled'), ('cancel', 'Bill Cancel'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
